// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/toast-variants/BoldBrand.tsx": () => import("../components/mockups/toast-variants/BoldBrand.tsx"),
  "./components/mockups/toast-variants/LightCard.tsx": () => import("../components/mockups/toast-variants/LightCard.tsx"),
  "./components/mockups/toast-variants/Pill.tsx": () => import("../components/mockups/toast-variants/Pill.tsx")
};
