// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/toast-variants/BoldBrand.tsx": () => import("../components/mockups/toast-variants/BoldBrand.tsx"),
  "./components/mockups/toast-variants/LightCard.tsx": () => import("../components/mockups/toast-variants/LightCard.tsx"),
  "./components/mockups/toast-variants/Pill.tsx": () => import("../components/mockups/toast-variants/Pill.tsx"),
  "./components/mockups/investment-section/Current.tsx": () => import("../components/mockups/investment-section/Current.tsx"),
  "./components/mockups/investment-section/InputDireto.tsx": () => import("../components/mockups/investment-section/InputDireto.tsx"),
  "./components/mockups/investment-section/JaInvestido.tsx": () => import("../components/mockups/investment-section/JaInvestido.tsx"),
  "./components/mockups/investment-section/ParaInvestir.tsx": () => import("../components/mockups/investment-section/ParaInvestir.tsx"),
  "./components/mockups/investment-section/Segmented.tsx": () => import("../components/mockups/investment-section/Segmented.tsx"),
  "./components/mockups/investment-section/Stepped.tsx": () => import("../components/mockups/investment-section/Stepped.tsx")
};
